<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250216113744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE quiz_app.answer_id_answer_seq CASCADE');
        $this->addSql('DROP SEQUENCE quiz_app.question_id_question_seq CASCADE');
        $this->addSql('CREATE TABLE answer_ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE quiz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, creator VARCHAR(255) NOT NULL, completed INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE register (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nick VARCHAR(63) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nick VARCHAR(180) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('DROP TABLE quiz_app.answer');
        $this->addSql('DROP TABLE quiz_app.question_answer');
        $this->addSql('DROP TABLE quiz_app.question');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA quiz_app');
        $this->addSql('CREATE SEQUENCE quiz_app.answer_id_answer_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE quiz_app.question_id_question_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE quiz_app.answer (id_answer INT DEFAULT quiz_app.answer_id_answer_seq NOT NULL, answer VARCHAR(128) DEFAULT NULL, PRIMARY KEY(id_answer))');
        $this->addSql('CREATE TABLE quiz_app.question_answer (id_question INT DEFAULT NULL, id_answer INT DEFAULT NULL, is_correct BOOLEAN DEFAULT NULL)');
        $this->addSql('CREATE TABLE quiz_app.question (id_question INT DEFAULT quiz_app.question_id_question_seq NOT NULL, question VARCHAR(128) DEFAULT NULL, PRIMARY KEY(id_question))');
        $this->addSql('DROP TABLE answer_');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE quiz');
        $this->addSql('DROP TABLE register');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
